unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
bind-key C-d detach-client

set -g set-titles
set -g set-titles-string '#{pane_title}'
set -g history-limit 20000

source ~/.config/tmux/tmuxline.conf

bind r source-file ~/.config/tmux/tmux.conf
bind F5 source-file ~/.config/tmux/tmux.conf
set -g mouse on
bind -T copy-mode WheelUpPane send -N1 -X scroll-up
bind -T copy-mode WheelDownPane send -N1 -X scroll-down


bind c neww -c '#{pane_current_path}'
bind '|' split-pane -h -c '#{pane_current_path}'
unbind l
bind h select-pane -L
bind C-h select-pane -L
bind j select-pane -D
bind C-j select-pane -D
bind k select-pane -U
bind C-k select-pane -U
bind l select-pane -R
bind C-l select-pane -R

bind C-t display-popup -d "#{pane_current_path}" -E 'bash'
bind C-r display-popup -d "#{pane_current_path}" -w 80% -h 80% -E 'ranger'
bind C-n display-popup -E 'bash -i -c "read -p \"Session name: \" name; tmux new-session -d -s \$name && tmux switch-client -t \$name"'
bind C-p display-popup -E "tmux list-sessions | sed -E 's/:.*$//' | grep -v \"~$(tmux display-message —p '#S')\$\" | sk --reverse | xargs tmux switch-client -t"
